
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wwatik <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/22 02:02:37 by wwatik            #+#    #+#              #
#    Updated: 2022/10/29 00:23:36 by wwatik           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
NAME = libft.a
AR = ar rc
SRCS = ft_isdigit.c ft_memset.c ft_strjoin.c ft_strtrim.c ft_isprint.c\
ft_strlcat.c ft_substr.c ft_atoi.c ft_itoa.c \
ft_strlcpy.c ft_tolower.c ft_bzero.c ft_strlen.c \
ft_toupper.c ft_calloc.c ft_memchr.c  ft_isalnum.c \
ft_memcmp.c ft_split.c ft_strncmp.c ft_isalpha.c ft_memcpy.c ft_strchr.c\
ft_strnstr.c ft_isascii.c ft_memmove.c ft_strdup.c ft_strrchr.c \
ft_strmapi.c ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c \
ft_putendl_fd.c ft_putnbr_fd.c

CC = cc -Wall -Wextra -Werror
OBJS = ${SRCS:%.c=%.o}

all : $(NAME)
$(NAME) : $(OBJS) libft.h
%.o : %.c libft.h
	$(CC) -c $<
	$(AR) $(NAME) $@
clean :
	rm -f $(OBJS)
fclean : clean
	rm -f $(NAME)
re : fclean $(NAME)
.PHONY : all clean fclean re